version: "3.1"
services:
    www:
        build: .
        container_name: Debian
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
            #- ./etc/apache2/apache2.conf:/etc/apache2/apache2.conf
            #- ./etc/php/8.1/apache2/php.ini:/etc/php/8.1/apache2/php.ini
 
        command: tail -f /dev/null
       
        